usuario_homepage:
    path:     /
    defaults: { _controller: UsuarioBundle:Default:index }

login:
    path:     /login
    defaults: { _controller: UsuarioBundle:Default:login }

logout:
    path:     /logout
    defaults: { _controller: UsuarioBundle:Default:logout }    

inicio:
    path:     /inicio
    defaults: { _controller: UsuarioBundle:Default:inicio }

crearUsuario:
    path:     /crear
    defaults: { _controller: UsuarioBundle:Default:crear } 

guardar:
    path:     /guardar
    defaults: { _controller: UsuarioBundle:Default:guardar } 